---
# YAML documents begin with the document separator ---

# This playbook will log into vcenter den06 and power on the template VMs
-

  # Target: where our play will run and options it will run with
  hosts: localhost
  gather_facts: true

  # Variable: variables that will apply to the play, on all target systems
    
  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks: 
    - name: include vars
      include_vars:
        dir: '../group_vars'
        files_matching: 'den06.yml'

    - name: Set powerstate of a virtual machine to poweron
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: /"{{ datacenter_name }}"/WindowsTemplates/TestTemplates
        name: "{{ item.guest_name }}"
        state: poweredon
      loop:
        - { guest_name: 'test_win2k12_180808_NGS' }
        - { guest_name: 'test_win2016_111508_NGS' }

  # Handlers: handlers that are executed as a notify key from a task

  # Roles: list of roles to be imported into the play

# Three dots indicate the end of a YAML document
...